-- 기존 DB에 UNLIMITED 시리즈 타입 추가
-- Oracle: 체크 제약 교체

ALTER TABLE CUSTOM_GAME DROP CONSTRAINT CK_CG_SERIES_TYPE;

ALTER TABLE CUSTOM_GAME ADD CONSTRAINT CK_CG_SERIES_TYPE
    CHECK (SERIES_TYPE IN ('SINGLE', 'BO3', 'BO5', 'UNLIMITED'));

COMMENT ON COLUMN CUSTOM_GAME.SERIES_TYPE IS 'SINGLE / BO3 / BO5 / UNLIMITED';
